apiVersion: v1
kind: Service
metadata:
  name: customer-svc
spec:
  selector: 
    app: hotrodcustomer
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrodcustomer
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: hotrodcustomer
spec:
  selector:
    matchLabels:
      app: hotrodcustomer
  template:
    metadata:
      labels:
        app: hotrodcustomer
    spec:
      containers:
      - name: hotrodcustomer
        image: juanjcsr/hotrod:latest
        imagePullPolicy: Always
        args:
          - "customer"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
