apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector: 
    app: hotrodcustomer
  ports: 
    - port: 8080  
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: hotrod
spec:
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
        - name: hotrodfrontend
          image: juanjcsr/hotrod:latest
          imagePullPolicy: Always
          args: ["frontend"]
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 128Mi
              cpu: 200m