name: Go Publish

on:
  push:
    branches:
      - main
      - environments

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      
      - name: download deps
        run: go mod download

      - name: Build
        run: go build -v ./...

  dockerbuild:
    runs-on: ubuntu-latest
    needs:
      - build
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: |
          docker build -t juanjcsr/hotrodaction .
